CREATE TABLE PROJETO (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
);
CREATE TABLE TAREFA (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITULO VARCHAR(255) NOT NULL,
  DESCRICAO VARCHAR(1000),
  STATUS VARCHAR(50),
  DATA_CRIACAO TIMESTAMP NOT NULL,
  ID_PROJETO INTEGER NOT NULL,
  CONSTRAINT FK_TAREFA_PROJ FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO(ID)
);